version: "3"

services:
  web:
    image: zhaqiang/docker-demo_web:prod
    ports:
      - "80:3000"
    env_file:
      - .env/production/database
      - .env/production/web
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data
  db-migrator:
    image: zhaqiang/docker-demo_web:prod
    command: ["./wait-for", "--time-out=300", "database:5432", "--", "bin/rails", "db:migrate"]
    env_file:
      - .env/production/database
      - .env/production/web
    deploy:
      restart_policy:
        condition: none
volumes:
  db_data:
